version: "3"
services:
  node-app:
    build: .
    volumes:
      - .:/home/app
    ports:
      - 3000:3000
    command: nodemon server.js
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mymongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
